package com.heliam1.HowToBeFit.di;

import android.app.Application;
import com.heliam1.HowToBeFit.di.AppComponent;
import com.heliam1.HowToBeFit.di.AppModule;

public class HowToBeFitApplication extends Application {
    private AppComponent appComponent;

    @Override
    public void onCreate() {
        super.onCreate();

        // DaggerAppComponent Autogenerated Class in a folder called dagger under build
        appComponent = DaggerAppComponent.builder().appModule(new AppModule(this)).build();

        appComponent.inject(this);
    }

    public AppComponent getAppComponent() {
        return appComponent;
    }
}
